dist: trusty
sudo: false

language: node_js
node_js:
  - '8'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


before_script:
  - cd untitled1
  - npm install --silent

script:
  - cd untitled1
  - npm run build --prod
